apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sq-appender-01
spec:
  template:
    spec:
      containers:
        - image: ikubernetes/appender
          env:
            - name: MESSAGE
              value: " - Handled by SQ-01"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sq-appender-02
spec:
  template:
    spec:
      containers:
        - image: ikubernetes/appender
          env:
            - name: MESSAGE
              value: " - Handled by SQ-02"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sq-appender-03
spec:
  template:
    spec:
      containers:
        - image: ikubernetes/appender
          env:
            - name: MESSAGE
              value: " - Handled by SQ-03"
---
