apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: hello.icloud2native.com
  namespace: default
spec:
  ref:
    name: hello
    kind: Service
    apiVersion: serving.knative.dev/v1
